# This file should ensure the existence of records required to run the application in every environment (production,
# development, test). The code here should be idempotent so that it can be executed at any point in every environment.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Example:
#
#   ["Action", "Comedy", "Drama", "Horror"].each do |genre_name|
#     MovieGenre.find_or_create_by!(name: genre_name)
#   end

# categorias = [
#  "Lideranças",
#  "Segurança",
#  "Reconhecimento",
#  "Treinamento e Desenvolvimento",
#  "Planejamento e Bem Estar",
#  "Remuneração e Benefícios",
#  "Cultura e Pertencimento",
#  "Comunicação",
#  "Segurança Psicológica",
#  "Saúde Mental",
#  "NPS"
# ]

# categorias = [
# "Estrutura Física",
# "Condições De Trabalho",
# "Higiene E Limpeza",
# "Recursos E Equipamentos De Trabalho",
# "Atendimento De Serviços Gerais",
# "Serviços Gerais E Saúde Mental",
# "Diversidade E Inclusão",
# "NPS Censo"
# ]

# categorias.each do |nome|
#   Category.find_or_create_by!(name: nome)
# end

# puts "Categorias criadas com sucesso!"

# Codigo.create!([
#   { name: "ADAIR DE ALMEIDA", code: "CMW7WXL0" },
#   { name: "ADAIR ENERIO DE JESUS", code: "OSX0OJ4O" },
#   { name: "ADINEI MARTINS", code: "NVLBWOD4" },
#   { name: "ADRIAN BUCOSKI ROMAIKE", code: "DR6A126T" },
#   { name: "AILTON KREFF", code: "1KPQ6PAT" },
#   { name: "ALAN FELIPE BARTLE WASOIZNIK", code: "ZOUWBTSB" },
#   { name: "ALBERTO RAMON FRUTOS GONZALEZ", code: "7E6QI4SH" },
#   { name: "ALESSON SOUZA DA SILVA", code: "3PENCO1M" },
#   { name: "ALEXANDRE LOPEZ", code: "V5MTEFCV" },
#   { name: "ALEXANDRE LUIZ AREND", code: "HD1G2GPS" },
#   { name: "ALEXANDRE STRABELLI", code: "JM7FRSOV" },
#   { name: "ANDERSON ANASTACIO DUARTE", code: "2U4KQ15O" },
#   { name: "ANDERSON PACIFICO", code: "OSLA7XC9" },
#   { name: "ANDRE APARECIDO DA SILVA", code: "M7Z1ZY4P" },
#   { name: "ANDREI VIEIRA DOS SANTOS", code: "5H86SM35" },
#   { name: "BRUNA DE SOUZA PEREIRA", code: "0ODU3006" },
#   { name: "BRUNO SOBRINHO WEIBER", code: "ELPD0O1A" },
#   { name: "CARLOS EDUARDO DE CAMARGO ARANO", code: "L5THHP6U" },
#   { name: "CARLOS HENRIQUE OLIVEIRA DOS SANTOS", code: "Y52LH8JR" },
#   { name: "CELIO MEDEIROS MOREIRA", code: "O1WB0LZ8" },
#   { name: "CESAR ALEXANDER MEDINA PERAZA", code: "GZ0GBQ4F" },
#   { name: "CLEIDINEI NEVES DE SOUZA", code: "KS6MMHCU" },
#   { name: "CLEISTON ALEXANDRE DE SOUZA AMARAL", code: "86S5OKXZ" },
#   { name: "CRISTIANO MEIRA DE JESUS", code: "1JGCPSVR" },
#   { name: "DAVID LUCAS DE JESUS", code: "6U2OF47F" },
#   { name: "DEOCLIDES RODRIGUES SILVA DA CRUZ", code: "DYG5JTFR" },
#   { name: "DOUGLAS ALVES RIBEIRO", code: "CFI6ZD8M" },
#   { name: "DOUGLAS MIGUEL ROMAGNA", code: "1FSYLL8F" },
#   { name: "EDER DE FREITAS SILVA", code: "1V5SPZO0" },
#   { name: "EDER LUCIANO JOSE VIEIRA", code: "E0WQWO69" },
#   { name: "EDSON BLOCKI DOS SANTOS", code: "TNUQW90H" },
#   { name: "EDSON JOSE DA SILVA", code: "AQ0A4NKQ" },
#   { name: "EDSON RAUL BATISTA JUNIOR", code: "4SH00LDZ" },
#   { name: "EDUARDO EUZEBIO DOS SANTOS", code: "1M2GJVEA" },
#   { name: "EDUARDO GABRIEL FRANCO ALVAREZ", code: "7CBGD935" },
#   { name: "ELSO VAZ DE OLIVEIRA", code: "HSB9D9FA" },
#   { name: "EMILLY EDUARDA FERREIRA BAIAO", code: "ZERINUCL" },
#   { name: "ERCIO GOMES JUNIOR", code: "S2CNRNVK" },
#   { name: "ERICK MATHEUS FERREIRA DE ANDRADE", code: "C2HCNYNN" },
#   { name: "ERIVALDO UMBERTO DOS SANTOS", code: "FCGQVO4U" },
#   { name: "EVERTON FELIPE CARNIEL", code: "2WRSTP2W" },
#   { name: "EZEQUIEL DA SILVA RODRIGUES", code: "9GI9IFKU" },
#   { name: "FABIO SILVA DE LIMA", code: "41EHL22Y" },
#   { name: "FELIPE DE OLIVEIRA PORTO", code: "K98C9OA0" },
#   { name: "FELIPE MORAIS DE SOUZA", code: "RW5FJMBT" },
#   { name: "FELIPE SANTIAGO VALDEZ MARINO", code: "Y4BPZC1Q" },
#   { name: "FERNANDO ALVES DE OLIVEIRA", code: "0FEI4JX3" },
#   { name: "FERNANDO ALVES VICENTE", code: "5OLGFI8R" },
#   { name: "FRANECIR OLIVEIRA DA SILVA", code: "DOUC6ZKN" },
#   { name: "GABRIEL GONZALEZ MARCONDES", code: "AKG6I1QI" },
#   { name: "GABRIELA FERNANDES MOMBELLI", code: "NXM01RCM" },
#   { name: "GILMAR OLEGINI PRETO", code: "Z3OW8T1T" },
#   { name: "GIOVANI DE SOUZA ORTIZ", code: "FAFUAYRN" },
#   { name: "GUILHERME BOURSCHEIDT", code: "WGTH1HAP" },
#   { name: "GUSTAVO HENRIQUE VIEIRA DA SILVA", code: "QN46D75R" },
#   { name: "HUMBERTO TEIXEIRA D AVILA", code: "CSJ0EAM6" },
#   { name: "IAGOR RAFAEL BAIL DA SILVA", code: "9RYMU6HC" },
#   { name: "IGOR DORIGON DA ROCHA", code: "5M5UIZ7Y" },
#   { name: "JEAN VITOR FERNANDES MARTENS", code: "MAYRV7MK" },
#   { name: "JEFERSON RODRIGUES", code: "5OO9DL0U" },
#   { name: "JIAN JORGE FRANCO", code: "MMW3B651" },
#   { name: "JOSE GERARDO NEUS AGRINZONES", code: "009K0UTF" },
#   { name: "JOSE MARIA GONZAGA", code: "O1CQ0R1I" },
#   { name: "JOSENILSON COIMBRA DOS SANTOS", code: "QS3361UO" },
#   { name: "JOSIAS VIEIRA DE OLIVEIRA", code: "557Y3W9R" },
#   { name: "KAMILA VITORIA MOISES DE MATTOS RAMOS", code: "UE38X750" },
#   { name: "KAUAN CARLOS BARBOSA", code: "6HHHW2HR" },
#   { name: "KAUANY DE ARAUJO CAMARGO", code: "5K2CEJUI" },
#   { name: "KEBERSON PAULO TROIAN", code: "A7JYZPIO" },
#   { name: "KENEDI ROBERTO TROIAN", code: "7GT69HPT" },
#   { name: "LEONARDO LEITE SANTANA", code: "EVXRJVBR" },
#   { name: "LEONARDO MORAES GLEN", code: "ZHOJW9U1" },
#   { name: "LUCAS DA CRUZ SALOMAO", code: "8HP8EMR6" },
#   { name: "LUCAS HENRIQUE FARIAS DA SILVA", code: "NHMDLXBH" },
#   { name: "MAICON CARVALHO", code: "IQKEI3XV" },
#   { name: "MARCELLO ALVES DA SILVA", code: "FTGFWXWJ" },
#   { name: "MARCELO DE FREITAS BENITEZ", code: "5RFNJ4YX" },
#   { name: "MARCIO WILLIANS DIAS", code: "JOE1IKYZ" },
#   { name: "MARCOS DA SILVA PRADO", code: "RK7QGOF8" },
#   { name: "MARCOS FIGUEIREDO", code: "AIB9WC7O" },
#   { name: "MATHEUS HENRIQUE NASCIMENTO", code: "WN9W8KRO" },
#   { name: "MATHEUS LEONARDO DE SESARO", code: "078CGH1N" },
#   { name: "MAYRA MILENA DE ASSUNCAO", code: "4ZJ2RIIU" },
#   { name: "MICHAEL RODRIGUES DOS SANTOS", code: "JLYMO2AL" },
#   { name: "NICKOLAS WESLEY DA COSTA", code: "VTMWGTVB" },
#   { name: "OSMAR ANTONIO CAMARGO", code: "73T7O0ZL" },
#   { name: "PATRICK WILLIAM DE SOUZA SILVA", code: "TOQFMD2A" },
#   { name: "PAULO EDSON DE OLIVEIRA", code: "RYAWFPIZ" },
#   { name: "PAULO VICTOR RODRIGUES DE OLIVEIRA", code: "8AC52GCF" },
#   { name: "PEDRO LUCAS DA SILVA ROCHA", code: "D1X6GK4H" },
#   { name: "PEDRO ROBERTO VIEIRA DE SOUZA", code: "59GAZIE4" },
#   { name: "RAFAEL BATISTA DOS SANTOS", code: "U93NGX3I" },
#   { name: "RAFAEL COSMANN PEREIRA", code: "WNYUH5KG" },
#   { name: "REMULO MIRANDA ANDRADE", code: "0YFZG1N2" },
#   { name: "RENATO FERNANDES", code: "GZWV733F" },
#   { name: "ROBERTO VAZ JUNIOR", code: "QJ27OFV2" },
#   { name: "RODRIGO FIRMINO DE ABREU", code: "GUCINW4V" },
#   { name: "ROMARIO CRISAN DOS SANTOS", code: "ZWBUF3ZC" },
#   { name: "SANTIAGO MATIAS SCHMITZ", code: "24ZC746E" },
#   { name: "SIDENEI GUERRA", code: "L1GQ91Y9" },
#   { name: "VINICIUS GRAMINHO", code: "30LYV3V0" },
#   { name: "VITOR MANOEL MATOS RIBEIRO DA ROCHA", code: "GYO6JDA9" },
#   { name: "WELLINTON DO NASCIMENTO STEIN", code: "N314BMDM" },
#   { name: "YOEL CUADRADO DAZA", code: "B3M35UMA" }
# ])
